apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner.my-apps.tap.20240508151339.0.0+build.6aff574
spec:
  refName: where-for-dinner.my-apps.tap
  version: 20240508151339.0.0+build.6aff574
  releaseNotes: |
    Release v20240508151339.0.0+build.6aff574 of package where-for-dinner.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tap-ci/ci-pipeline/apps-08-05-2024-11-17-27-618630505/where-for-dinner-my-apps-bundle@sha256:b8b56d7ca9f6cf47441d69233534b96217f4d19bfeb75df01d5b1d49e4d8b4de
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

